Make SkiaPixelBuffer public
WildernessLabs/Meadow.Foundation pull request #966
Opened 2024-05-03 08:56 UTC by pekkah

WriteBuffer optimization expects the buffer types to match not the actual format of the pixels. To take advantage of the optimization you should  be able to create matching buffer type.

2024-05-04 22:39 UTC, adrianstevens approved these changes

2024-05-21 10:56 UTC, pekkah commented
@adrianstevens is this getting merged?

2024-05-22 02:51 UTC, adrianstevens commented
Thx @pekkah, apologies, I didn't think it was needed after the recent fixes. I don't mind making this class public but we do need to add xml comments to all of the public properties / methods.

2024-05-22 02:51 UTC, adrianstevens requested changes
Just need to add XML comments - can probably run it through Chat GPT

2024-06-02 02:40 UTC, merged